//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace insaatProjesi.Models.Entitiy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbInsaatProjesiEntities2 : DbContext
    {
        public dbInsaatProjesiEntities2()
            : base("name=dbInsaatProjesiEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_hakkimizda> tbl_hakkimizda { get; set; }
        public virtual DbSet<tbl_calisanlar> tbl_calisanlar { get; set; }
        public virtual DbSet<tbl_iletisim> tbl_iletisim { get; set; }
        public virtual DbSet<tbl_anasayfa> tbl_anasayfa { get; set; }
        public virtual DbSet<tbl_hizmetler> tbl_hizmetler { get; set; }
        public virtual DbSet<tbl_projeler> tbl_projeler { get; set; }
        public virtual DbSet<tbl_admin> tbl_admin { get; set; }
    }
}
