//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace insaatProjesi.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hakkimizda
    {
        public int ID { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> CalisanSayisi { get; set; }
        public Nullable<int> MusteriMemnuniyeti { get; set; }
        public Nullable<int> TamamlanmisProjeler { get; set; }
        public Nullable<int> DevamEdenProjeler { get; set; }
        public string Soru1 { get; set; }
        public string Cevap1 { get; set; }
        public string Soru2 { get; set; }
        public string Cevap2 { get; set; }
        public string Soru3 { get; set; }
        public string Cevap3 { get; set; }
        public string Soru4 { get; set; }
        public string Cevap4 { get; set; }
        public string Soru5 { get; set; }
        public string Cevap5 { get; set; }
        public string Soru6 { get; set; }
        public string Cevap6 { get; set; }
    }
}
