//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace insaatProjesi.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_projeler
    {
        public int ID { get; set; }
        public string ProjeAdı { get; set; }
        public string ProjeAciklama { get; set; }
        public string ProjeDurum { get; set; }
        public string projeResim { get; set; }
    }
}
