//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace insaatProjesi.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_anasayfa
    {
        public int ID { get; set; }
        public string SliderFoto1 { get; set; }
        public string SliderFoto2 { get; set; }
        public string SliderFoto3 { get; set; }
        public string Slider1Soz1 { get; set; }
        public string Slider1Soz2 { get; set; }
        public string Slider2Soz1 { get; set; }
        public string Slider2Soz2 { get; set; }
        public string Slider3Soz1 { get; set; }
        public string Slider3Soz2 { get; set; }
        public string Baslik1 { get; set; }
        public string Aciklama1 { get; set; }
        public string Baslik2 { get; set; }
        public string Aciklama2 { get; set; }
        public string Baslik3 { get; set; }
        public string Aciklama3 { get; set; }
        public string VideoLink { get; set; }
        public string Yorumcu1Ad { get; set; }
        public string Yorumcu1Meslek { get; set; }
        public string Yorumcu1Yorum { get; set; }
        public string Yorumcu2Ad { get; set; }
        public string Yorumcu2Meslek { get; set; }
        public string Yorumcu2Yorum { get; set; }
        public string Yorumcu3Ad { get; set; }
        public string Yorumcu3Meslek { get; set; }
        public string Yorumcu3Yorum { get; set; }
    }
}
